### PR TITLE
removing minishift support from makefiles and updating readme

### PR DESCRIPTION
**Pull request by ranakan19**
fix wrt to: https://issues.redhat.com/browse/CRT-904

### CODE REVIEW

**Review by xcoulon — APPROVED** [review]

**Review by alexeykazakov — COMMENTED** [review]
Well... DevCluster is not part of Sandbox :)
And it does support minishift since it's a regular app which happen to be provisioned to OpenShift. It's not an operator or something like this.

**Comment by ranakan19** [comment]
> appen to be provisioned to OpenS

oh, my bad! 
I could just close this PR then, would that be okay @alexeykazakov ?

**Comment by MatousJobanek** [comment]
@alexeykazakov Just out of curiosity - do you really still use Minishift for that? Or would you use it?

**Comment by alexeykazakov** [comment]
I used it during development before switching to Sandbox.

**Review by alexeykazakov — APPROVED** [review]
But I'm fine with deleting it.

**Pull request merged**
